### PR TITLE
Translations Japanese

### PR DESCRIPTION
**Pull request by Blank-1973**
General file 100%
Main file about 100%

Complete

### CODE REVIEW

**Comment by Wolfteam** [comment]
Awesome, will you complete the remaining parts ?

**Comment by Blank-1973** [comment]
Now translating weapons
These are over
Catalyst
Bow
Sword

**Comment by Wolfteam** [comment]
> Now translating weapons
> These are over
> Catalyst
> Bow
> Sword

Oka, take your time and let me know when you are done

**Comment by Blank-1973** [comment]
Weapon translation finished

**Comment by Blank-1973** [comment]
All translations have been done

**Comment by Wolfteam** [comment]
Awesome work 👍 
I left some comments, though I'm still gonna merge this one so I can push a beta update with your translations (should be up in 3hrs ~).
Btw maybe you could join the [Discord Server](https://discord.com/invite/A8SgudQMwP) so I can add you to a private channel and talk there

**Comment by Blank-1973** [comment]
Thank you.
The name of Discord is 𝕽𝖚𝖗𝖎#3080

**Pull request merged**
