### PR TITLE
Feature/french translations

### PR DESCRIPTION
**Pull request by therealcorwin**
Translation : Ayaka Kamisato
Translation : Traveler (electro)
Translation : Traveler (electro)
Translation : Weapons patch V2.0
Translation : Materials patch V2.0

### CODE REVIEW

**Comment by Wolfteam** [comment]
Left some comments

image

**Review by therealcorwin — COMMENTED** [review]
Fix Ok :)

**Comment by Wolfteam** [comment]
@therealcorwin Forgot to mention that I pushed a new beta with your changes yesterday

**Comment by therealcorwin** [comment]
@Wolfteam, I know :) I'm checking all my work and i will make some corrections this weekend.

**Comment by therealcorwin** [comment]
Hi @Wolfteam :)

Is there a tips to center a weapon name easily or not because using "\t" is not very sexy ^_^. Or, i use a normal line break and don't center the text ?

**Review by Wolfteam — COMMENTED** [review]
> Hi @Wolfteam :)
> 
> Is there a tips to center a weapon name easily or not because using "\t" is not very sexy ^_^. Or, i use a normal line break and don't center the text ?

In the weapon list, the names are always centered.
In the weapon detail, the name is aligned to the start
So in the end, there's on need to align the names in the json file

**Comment by therealcorwin** [comment]
> 
> 
> > Hi @Wolfteam :)
> > Is there a tips to center a weapon name easily or not because using "\t" is not very sexy ^_^. Or, i use a normal line break and don't center the text ?
> 
> In the weapon list, the names are always centered.
> In the weapon detail, the name is aligned to the start
> So in the end, there's on need to align the names in the json file

For example, a too long weapon name in french : 

Arc1

It's not very nice. 

If i put a "\n"
Arc2
We can read the entire name, but in weapon description : 
Arc3

In the first picture, the name must adapt with the width of the frame, it will be nicer and usefull for the user, no ?

**Comment by Wolfteam** [comment]
> > > Hi @Wolfteam :)
> > > Is there a tips to center a weapon name easily or not because using "\t" is not very sexy ^_^. Or, i use a normal line break and don't center the text ?
> > 
> > 
> > In the weapon list, the names are always centered.
> > In the weapon detail, the name is aligned to the start
> > So in the end, there's on need to align the names in the json file
> 
> For example, a too long weapon name in french :
> 
> Arc1
> 
> It's not very nice.
> 
> If i put a "\n"
> Arc2
> We can read the entire name, but in weapon description :
> Arc3
> 
> In the first picture, the name must adapt with the width of the frame, it will be nicer and usefull for the user, no ?

1) yep that's the current beheaviour, otherwise some "cards" may become bigger than others, that's why I prefer to hide the overflow with the dots (....)

2) This will only work on certain resolutions, on bigger devices it will look weird

3) In the weapon details, if I'm not wrong, the name may take up to 2 lines.

**Comment by therealcorwin** [comment]
>     1. yep that's the current beheaviour, otherwise some "cards" may become bigger than others, that's why I prefer to hide the overflow with the dots (....)

May be, change dynamically the size of characters if the name is too long. With this all cards are equals., and we can read the complete name. 
 
>     2. This will only work on certain resolutions, on bigger devices it will look weird
 Yeah, it was just for the example ^^
>     3. In the weapon details, if I'm not wrong, the name may take up to 2 lines.
Yes, two lines :)

I lost sooooooooooooo many time with this fucking Java to emulate an android device and i haven't enough time to work on correction. I try during this week. The major part of translation is correct. Rest some cosmetic touch :)

**Pull request merged**
